// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: stock/stock.proto

package stockpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockStatus int32

const (
	StockStatus_Unknown      StockStatus = 0
	StockStatus_Sufficient   StockStatus = 1
	StockStatus_Insufficient StockStatus = 2
)

// Enum value maps for StockStatus.
var (
	StockStatus_name = map[int32]string{
		0: "Unknown",
		1: "Sufficient",
		2: "Insufficient",
	}
	StockStatus_value = map[string]int32{
		"Unknown":      0,
		"Sufficient":   1,
		"Insufficient": 2,
	}
)

func (x StockStatus) Enum() *StockStatus {
	p := new(StockStatus)
	*p = x
	return p
}

func (x StockStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StockStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_stock_stock_proto_enumTypes[0].Descriptor()
}

func (StockStatus) Type() protoreflect.EnumType {
	return &file_stock_stock_proto_enumTypes[0]
}

func (x StockStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StockStatus.Descriptor instead.
func (StockStatus) EnumDescriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{0}
}

type CheckAndFetchItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemWithQuantity    `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndFetchItemsRequest) Reset() {
	*x = CheckAndFetchItemsRequest{}
	mi := &file_stock_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndFetchItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndFetchItemsRequest) ProtoMessage() {}

func (x *CheckAndFetchItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndFetchItemsRequest.ProtoReflect.Descriptor instead.
func (*CheckAndFetchItemsRequest) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAndFetchItemsRequest) GetItems() []*ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckAndFetchItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    StockStatus            `protobuf:"varint,1,opt,name=StatusCode,proto3,enum=stock.StockStatus" json:"StatusCode,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndFetchItemsResponse) Reset() {
	*x = CheckAndFetchItemsResponse{}
	mi := &file_stock_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndFetchItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndFetchItemsResponse) ProtoMessage() {}

func (x *CheckAndFetchItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndFetchItemsResponse.ProtoReflect.Descriptor instead.
func (*CheckAndFetchItemsResponse) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAndFetchItemsResponse) GetStatusCode() StockStatus {
	if x != nil {
		return x.StatusCode
	}
	return StockStatus_Unknown
}

func (x *CheckAndFetchItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemWithQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        string                 `protobuf:"bytes,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemWithQuantity) Reset() {
	*x = ItemWithQuantity{}
	mi := &file_stock_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemWithQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemWithQuantity) ProtoMessage() {}

func (x *ItemWithQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemWithQuantity.ProtoReflect.Descriptor instead.
func (*ItemWithQuantity) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{2}
}

func (x *ItemWithQuantity) GetItemID() string {
	if x != nil {
		return x.ItemID
	}
	return ""
}

func (x *ItemWithQuantity) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        string                 `protobuf:"bytes,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	PriceID       string                 `protobuf:"bytes,4,opt,name=PriceID,proto3" json:"PriceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_stock_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetItemID() string {
	if x != nil {
		return x.ItemID
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetPriceID() string {
	if x != nil {
		return x.PriceID
	}
	return ""
}

var File_stock_stock_proto protoreflect.FileDescriptor

const file_stock_stock_proto_rawDesc = "" +
	"\n" +
	"\x11stock/stock.proto\x12\x05stock\"J\n" +
	"\x19CheckAndFetchItemsRequest\x12-\n" +
	"\x05Items\x18\x01 \x03(\v2\x17.stock.ItemWithQuantityR\x05Items\"s\n" +
	"\x1aCheckAndFetchItemsResponse\x122\n" +
	"\n" +
	"StatusCode\x18\x01 \x01(\x0e2\x12.stock.StockStatusR\n" +
	"StatusCode\x12!\n" +
	"\x05Items\x18\x02 \x03(\v2\v.stock.ItemR\x05Items\"F\n" +
	"\x10ItemWithQuantity\x12\x16\n" +
	"\x06ItemID\x18\x01 \x01(\tR\x06ItemID\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\x03R\bQuantity\"h\n" +
	"\x04Item\x12\x16\n" +
	"\x06ItemID\x18\x01 \x01(\tR\x06ItemID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bQuantity\x18\x03 \x01(\x03R\bQuantity\x12\x18\n" +
	"\aPriceID\x18\x04 \x01(\tR\aPriceID*<\n" +
	"\vStockStatus\x12\v\n" +
	"\aUnknown\x10\x00\x12\x0e\n" +
	"\n" +
	"Sufficient\x10\x01\x12\x10\n" +
	"\fInsufficient\x10\x022i\n" +
	"\fStockService\x12Y\n" +
	"\x12CheckAndFetchItems\x12 .stock.CheckAndFetchItemsRequest\x1a!.stock.CheckAndFetchItemsResponseB\x19Z\x17common/protobuf/stockpbb\x06proto3"

var (
	file_stock_stock_proto_rawDescOnce sync.Once
	file_stock_stock_proto_rawDescData []byte
)

func file_stock_stock_proto_rawDescGZIP() []byte {
	file_stock_stock_proto_rawDescOnce.Do(func() {
		file_stock_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_stock_proto_rawDesc), len(file_stock_stock_proto_rawDesc)))
	})
	return file_stock_stock_proto_rawDescData
}

var file_stock_stock_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stock_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stock_stock_proto_goTypes = []any{
	(StockStatus)(0),                   // 0: stock.StockStatus
	(*CheckAndFetchItemsRequest)(nil),  // 1: stock.CheckAndFetchItemsRequest
	(*CheckAndFetchItemsResponse)(nil), // 2: stock.CheckAndFetchItemsResponse
	(*ItemWithQuantity)(nil),           // 3: stock.ItemWithQuantity
	(*Item)(nil),                       // 4: stock.Item
}
var file_stock_stock_proto_depIdxs = []int32{
	3, // 0: stock.CheckAndFetchItemsRequest.Items:type_name -> stock.ItemWithQuantity
	0, // 1: stock.CheckAndFetchItemsResponse.StatusCode:type_name -> stock.StockStatus
	4, // 2: stock.CheckAndFetchItemsResponse.Items:type_name -> stock.Item
	1, // 3: stock.StockService.CheckAndFetchItems:input_type -> stock.CheckAndFetchItemsRequest
	2, // 4: stock.StockService.CheckAndFetchItems:output_type -> stock.CheckAndFetchItemsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stock_stock_proto_init() }
func file_stock_stock_proto_init() {
	if File_stock_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_stock_proto_rawDesc), len(file_stock_stock_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_stock_proto_goTypes,
		DependencyIndexes: file_stock_stock_proto_depIdxs,
		EnumInfos:         file_stock_stock_proto_enumTypes,
		MessageInfos:      file_stock_stock_proto_msgTypes,
	}.Build()
	File_stock_stock_proto = out.File
	file_stock_stock_proto_goTypes = nil
	file_stock_stock_proto_depIdxs = nil
}
