services:
  consul:
    image: hashicorp/consul:latest
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8400:8500"

  rabbit-mq:
    image: rabbitmq:4-management
    ports:
      - "8500:5672"
      - "8501:15672"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "8600:9411"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "8700:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8701:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  mysql:
    image: mysql:9
    restart: always
    ports:
      - "8800:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
