order:
  service-name: order
  http-host: 127.0.0.1
  http-port: 8101
  grpc-host: 127.0.0.1
  grpc-port: 8102

stock:
  service-name: stock
  grpc-host: 127.0.0.1
  grpc-port: 8202

payment:
  service-name: payment
  http-host: 127.0.0.1
  http-port: 8301

process:
  service-name: process

consul:
  host: 127.0.0.1
  port: 8400

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 8500

zipkin:
  host: 127.0.0.1
  port: 8600

mongo:
  user: root
  password: password
  host: 127.0.0.1
  port: 8700
  db-name: order
  collection-name: order

mysql:
  user: user
  password: password
  host: 127.0.0.1
  port: 8800
  db-name: stock

redis:
  host: 127.0.0.1
  port: 8900
  lock:
    expiration: 5s
    retry-number: 3
    retry-delay: 100ms
