order:
  service-name: order
  http-host: 127.0.0.1
  http-port: 8101
  grpc-host: 127.0.0.1
  grpc-port: 8102

stock:
  service-name: stock
  grpc-host: 127.0.0.1
  grpc-port: 8202

payment:
  service-name: payment
  http-host: 127.0.0.1
  http-port: 8301

consul:
  host: 127.0.0.1
  port: 8400

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 8500
