// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ports

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	CustomerID string             `json:"customerID"`
	Items      []ItemWithQuantity `json:"items"`
}

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// ItemWithQuantity defines model for ItemWithQuantity.
type ItemWithQuantity struct {
	ItemID   string `json:"itemID"`
	Quantity int64  `json:"quantity"`
}

// Response defines model for Response.
type Response struct {
	Data      map[string]interface{} `json:"data"`
	ErrorCode int64                  `json:"errorCode"`
	Message   string                 `json:"message"`
	TraceID   string                 `json:"traceID"`
}

// PostCustomerCustomerIdCreateJSONRequestBody defines body for PostCustomerCustomerIdCreate for application/json ContentType.
type PostCustomerCustomerIdCreateJSONRequestBody = CreateOrderRequest
